# Generated by Django 4.0.6 on 2022-10-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='vip_level',
            field=models.CharField(choices=[('VIP 1', 'VIP1'), ('VIP 2', 'VIP 2'), ('VIP 3', 'VIP 3'), ('VIP 4', 'VIP 4'), ('VIP 5', 'VIP 5'), ('VIP 6', 'VIP 6')], default='None', max_length=300, null=True),
        ),
    ]
